name: Publish to NPM and GPR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v1

      # Update package version and set up git
      - uses: actions/setup-node@v1
      - name: Update package version and setup git
        run: |
          npm install
          npm run build

  # Publish to NPM
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Publish to NPM
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/'
          scope: 'rollawaypoint'
      - name: Publish to NPM
        run: |
          npm config set https://registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  # Publish to GitHub Package Registry
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@rollawaypoint'
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_AUTH_TOKEN}}
